export const collections = {
    systems: [
        { 'id': 1, 'name': 'ახალი' },
        { 'id': 2, 'name': 'მიმდინარე' },
    ],
    currentBank: [
        { 'id': 1, 'name': 'ახალი' },
        { 'id': 2, 'name': 'მიმდინარე' },
    ],
    yesno: [
        { 'id': 0, 'name': 'არა' },
        { 'id': 1, 'name': 'კი' },
    ],
    tasks: [
        { 'id': 1, 'name': 'სესხის რეგისტრაცია' },
        { 'id': 2, 'name': 'სესხის გაცემა' }
    ],
    banks: [
        { 'id': 1, 'name': 'VTB' },
        { 'id': 2, 'name': 'BOG' },
        { 'id': 3, 'name': 'Procredit' },
        { 'id': 4, 'name': 'TBC' },
        { 'id': 5, 'name': 'Republic' },
        { 'id': 6, 'name': 'Liberty' },
        { 'id': 7, 'name': 'HSBC' },
        { 'id': 8, 'name': 'TaoPrivate' },
        { 'id': 9, 'name': 'BTA' },
        { 'id': 10, 'name': 'Basisbank' },
        { 'id': 11, 'name': 'Cartu' },
        { 'id': 12, 'name': 'KorStandard' },
        { 'id': 13, 'name': 'Constanta' },
        { 'id': 14, 'name': 'Progress' },
        { 'id': 15, 'name': 'Halikbank' },
        { 'id': 16, 'name': 'Ziraatbank' },
        { 'id': 17, 'name': 'Investbank' },
        { 'id': 18, 'name': 'AgroInvest' },
        { 'id': 19, 'name': 'სხვა' },
    ],
    cities: [
        { 'id': 1, 'name': "თბილისი" },
        { 'id': 2, 'name': "ბათუმი" },
        { 'id': 3, 'name': "ქუთაისი" },
        { 'id': 4, 'name': "რუსთავი" },
        { 'id': 5, 'name': "გორი" },
        { 'id': 6, 'name': "ზუგდიდი" },
        { 'id': 7, 'name': "ფოთი" },
        { 'id': 8, 'name': "ხაშური" },
        { 'id': 9, 'name': "სამტრედია" },
        { 'id': 10, 'name': "სენაკი" },
        { 'id': 11, 'name': "ზესტაფონი" },
        { 'id': 12, 'name': "მარნეული" },
        { 'id': 13, 'name': "თელავი" },
        { 'id': 14, 'name': "ახალციხე" },
        { 'id': 15, 'name': "ქობულეთი" },
        { 'id': 16, 'name': "ოზურგეთი" },
        { 'id': 17, 'name': "კასპი" },
        { 'id': 18, 'name': "ჭიათურა" },
        { 'id': 19, 'name': "წყალტუბო" },
        { 'id': 20, 'name': "საგარეჯო" },
        { 'id': 21, 'name': "გარდაბანი" },
        { 'id': 22, 'name': "ბორჯომი" },
        { 'id': 23, 'name': "ტყიბული" },
        { 'id': 24, 'name': "ხონი" },
        { 'id': 25, 'name': "ბოლნისი" },
        { 'id': 26, 'name': "ახალქალაქი" },
        { 'id': 27, 'name': "გურჯაანი" },
        { 'id': 28, 'name': "მცხეთა" },
        { 'id': 29, 'name': "ყვარელი" },
        { 'id': 30, 'name': "ახმეტა" },
        { 'id': 31, 'name': "ქარელი" },
        { 'id': 32, 'name': "ლანჩხუთი" },
        { 'id': 33, 'name': "დუშეთი" },
        { 'id': 34, 'name': "საჩხერე" },
        { 'id': 35, 'name': "დედოფლისწყარო" },
        { 'id': 36, 'name': "ლაგოდეხი" },
        { 'id': 37, 'name': "ნინოწმინდა" },
        { 'id': 38, 'name': "აბაშა" },
        { 'id': 39, 'name': "წნორი" },
        { 'id': 40, 'name': "თერჯოლა" },
        { 'id': 41, 'name': "მარტვილი" },
        { 'id': 42, 'name': "ხობი" },
        { 'id': 43, 'name': "წალენჯიხა" },
        { 'id': 44, 'name': "ვანი" },
        { 'id': 45, 'name': "ბაღდათი" },
        { 'id': 46, 'name': "ვალე" },
        { 'id': 47, 'name': "თეთრიწყარო" },
        { 'id': 48, 'name': "დმანისი" },
        { 'id': 49, 'name': "ონი" },
        { 'id': 50, 'name': "წალკა" },
        { 'id': 51, 'name': "ამბროლაური" },
        { 'id': 52, 'name': "სიღნაღი" },
        { 'id': 53, 'name': "ცაგერი" },
        { 'id': 54, 'name': "ჯვარი" },
        { 'id': -1, 'name': "სხვა" },
    ]
}